Movie Recommendation Website /src/website/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from . import db
from flask_login import login_required, current_user
from .models import Recommendation, WatchedMovie
from .functions import QuizFunctions, MovieCards, DBAdditions, GeneralFunctions

#set up a blueprint for the flask application
views = Blueprint('views', __name__) 

# create a route 
@views.route('/')
@views.route('/home')
@login_required
#Changed this ****
def home():
    user_id = current_user.id
    return render_template("home.html", user=current_user)

@views.route('/profile', methods=['GET', 'POST'])
@login_required	
def profile():
    user_id = current_user.id
    recommended_ids = [recommended.movie_id for recommended in Recommendation.query.filter_by(user_id=user_id).all()]
    watched_ids = [watched.movie_id for watched in WatchedMovie.query.filter_by(user_id=user_id).all()]
    if request.method == 'POST':
        watched_items = [int(request.form[key]) for key in request.form if key.startswith('w')]
        """for recommendation_id in selected_recommendations:
            recommendation = Recommendation.query.get(recommendation_id)
            if recommendation:
                watched_movie = WatchedMovie(user_id=user_id, movie_id=recommendation.movie_id)
                db.session.add(watched_movie)

        db.session.commit()"""
    displayed_recommendations = MovieCards.display_information(recommended_ids)
    displayed_watched = MovieCards.display_information(watched_ids)
    return render_template('profile.html', user = current_user, displayed_recommendations=displayed_recommendations, displayed_watched=displayed_watched )
	
	
@views.route('/quiz', methods=['GET', 'POST'])
@login_required
def quiz():
    return render_template('quiz.html', user=current_user)

@views.route('/quizsimilar', methods=['GET', 'POST'])
@login_required
def quiz_similar():
    user_id = current_user.id

    if request.method == 'POST':
        thirtyr = session.get('thirtyr', [])
        tempr = session.get('tempr', [])
        watched_items = [int(request.form[key]) for key in request.form if key.startswith('w')]
        not_interested_items = [int(request.form[key]) for key in request.form if key.startswith('ni')]

        all_affected_items = watched_items + not_interested_items
        for movie_id in all_affected_items:
            if movie_id in watched_items:
                DBAdditions.add_watched(user_id, movie_id)
            elif movie_id in not_interested_items:
                DBAdditions.add_not_interested(user_id, movie_id)
                #remove from recommendations
            thirtyr.remove(movie_id)
            tempr.remove(movie_id)
        if not all_affected_items:
            DBAdditions.add_recommended(user_id, tempr)
        session['thirtyr'] = thirtyr 
        session['tempr'] = tempr
        #regenerate thirtyr and tempr when they are less than 10

    if 'runqs1' not in session:
        session['runqs1'] = True
        thirtyr = QuizFunctions.generate_similar_quiz_results(user_id)
        tempr = thirtyr[:10]
        session['thirtyr'] = thirtyr
        session['tempr'] = tempr

    displayed = MovieCards.display_information(session.get('tempr', []))
    return render_template('quizsimilar.html', user=current_user, displayed=displayed)
 
@views.route('/newquiz', methods=['GET', 'POST'])
@login_required
def quiz_new():
    user_id = current_user.id
    genre_list = ['Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family',
                  'Fantasy', 'Film-Noir', 'History', 'Horror', 'Music', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Short',
                  'Sport', 'Thriller', 'War', 'Western']

    if request.method == 'POST':
        if 'selected_genres' not in session:
            genre_select = [request.form[key] for key in request.form if key.startswith('s')]
            session['selected_genres'] = genre_select
            return redirect(url_for('views.quiz_new'))
        if 'selected_actors' not in session:
            actor_select = [request.form[key] for key in request.form if key.startswith('a')]
            session['selected_actors'] = actor_select
            return redirect(url_for('views.quiz_new'))

        if 'selected_directors' not in session:
            director_select = [request.form[key] for key in request.form if key.startswith('d')]
            session['selected_directors'] = director_select
            return redirect(url_for('views.quiz_new'))

        if 'selected_languages' not in session:
            language_select = [request.form[key] for key in request.form if key.startswith('l')]
            session['selected_languages'] = language_select
            return redirect(url_for('views.quiz_new'))

        if 'selected_movies' not in session:
            movies_selected = [int(request.form[key]) for key in request.form if key.startswith('w')]
            #movies_selected_havent_watched = [int(request.form[key]) for key in request.form if key.startswith('dw')]
            for movie in movies_selected:
                DBAdditions.add_watched(user_id, movie)
            session['selected_movies'] = movies_selected
            return redirect(url_for('views.quiz_new'))

        if 'writer_info' not in session:
            movies_liked = [int(request.form[key]) for key in request.form if key.startswith('li')]
            movies_didnt_like = [int(request.form[key]) for key in request.form if key.startswith('dl')]
            for movie in movies_didnt_like:
                DBAdditions.add_not_interested(user_id, movie)
            session['writer_info'] = movies_liked
            return redirect(url_for('views.quiz_new'))

    if 'selected_genres' not in session:
        return render_template('newquiz.html', user=current_user, stage='genre_selection', genre_list=genre_list)

    if 'selected_actors' not in session:
        selected_genres = session.get('selected_genres', [])
        actor_list = QuizFunctions.selection(selected_genres, 1) if selected_genres else {}
        return render_template('newquiz.html', user=current_user, stage='actor_display', actor_list=actor_list)

    if 'selected_directors' not in session:
        selected_genres = session.get('selected_genres', [])
        director_list = QuizFunctions.selection(selected_genres, 2) if selected_genres else {}
        return render_template('newquiz.html', user=current_user, stage='director_display', director_list=director_list)

    if 'selected_languages' not in session:
        language_list = ['American Sign Language', 'Arabic', 'Bangla', 'Cantonese', 'Chaozhou', 'Chinese', 'Czech', 'Dinka', 
                         'Dutch', 'English', 'Finnish', 'French', 'German', 'Greek', 'Hebrew', 'Hindi', 'Indonesian', 'Irish', 
                         'Italian', 'Japanese', 'Korean', 'Latin', 'Mandarin', 'North American Indian', 'Nepali','Persian', 
                         'Portuguese', 'Russian', 'Spanish', 'Turkish']
        return render_template('newquiz.html', user=current_user, stage='language_display', language_list=language_list)
    
    if 'selected_movies' not in session:
        movie_list = QuizFunctions.generate_combinations(session['selected_genres'], session['selected_actors'], session['selected_directors'], [])
        displayed = MovieCards.display_information(movie_list[:20])
        session['movies_displayed'] = movie_list
        return render_template('newquiz.html', user=current_user, stage='movie_display', displayed=displayed)

    if 'writer_info' not in session:
        show_watched = session.get('selected_movies')
        new_displayed = MovieCards.display_information(show_watched)
        return render_template('newquiz.html', user=current_user, stage='movie_display2', displayed=new_displayed)

    writer_ids = session.get('writer_info')
    writers = QuizFunctions.get_writers(writer_ids)
    movie_list = QuizFunctions.generate_combinations(session['selected_genres'],  session['selected_actors'], session['selected_directors'], writers)
    new_list = GeneralFunctions.remove_watched_ids(movie_list, user_id)
    new_list = new_list[:10]
    for t in new_list:
        new_recommendation = Recommendation(user_id=user_id, movie_id=t)
        db.session.add(new_recommendation)
    db.session.commit()
    #remove old recommendtions, always run reset after this too

    displayed = MovieCards.display_information(new_list)
    return render_template('newquiz.html', user=current_user, stage='movie_display3', displayed=displayed)



@views.route('/reset_quiz')
@login_required
def reset_quiz():
    session.pop('selected_genres', None)
    session.pop('selected_actors', None)
    session.pop('selected_directors', None)
    session.pop('selected_languages', None)
    session.pop('selected_movies', None)
    session.pop('writer_info', None)
    return redirect(url_for('views.quiz_new'))



Movie Recommendation Website /src/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- using bootstrap to make the css look nicer-->
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous" />
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="static/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
    <!-- Jinga - Python support for web -->
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>

    <header>
        <h2 class="logo" style='font-family: Dancing Script; font-size: 50px;'>Scene Seeker</h2>
        <nav class="navigation">
            {% if user.is_authenticated %}
            <a href="/" class="home">Home</a>
            <a href="/quiz" class="quiz">Quizzes</a>
            <div class="dropdown">
                <a class="profile-button" style="color: #fff;">Profile<span class="arrow-down"></span></a>
                <div class="dropdown-content">
                    <a href="/profile">Go to my Profile</a>
                    <a href="/change_username">Change Username</a>
                    <a href="/change_password">Change Password</a>
                    <a href="/change_email">Change Email</a>
                </div>
            </div>
            <a href="/logout" class="logout">Logout</a>
            {% else %}
            <a class="btnLogin-popup" href="/login">Login</a>
            <a class="btnLogin-popup" href="/sign-up">Sign Up</a>
            {% endif %}
        </nav>
    </header>

    <!-- <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="/">Scene Seeker</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarResponsive"
        aria-controls="navbarResponsive"
        aria-expanded="false"
        aria-label="Toggle navigation"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" id="home" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="quiz" href="/quiz">Quiz</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href=# id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Profile
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="profile">Go to my Profile</a></li>
                  <li><a class="dropdown-item" href="change_username">Change Username</a></li>
                  <li><a class="dropdown-item" href="change_password">Change Password</a></li>
                  <li><a class="dropdown-item" href="change_email">Change Email</a></li>
              </ul>
          </li>
            <li class="nav-item">
              <a class="nav-link" id="logout" href="/logout">Logout</a>
            </li>
          </ul>
          <! <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a> -->
    <!-- {% else %}
    <ul class="navbar-nav ms-auto">
      <li class="nav-item">
        <a class="nav-link" id="login" href="/login">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="signUp" href="/sign-up">Sign Up</a>
      </li>
    </ul>
     <a class="nav-item nav-link" id="login" href="/login">Login</a>
    <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a> -->
    <!-- {% endif %}
        </div>
      </div>
    </nav> -->
    {% with messages = get_flashed_messages(with_categories=true)%}

    {% if messages %}
    {% for category, message in messages %}
    {% if category == 'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}

    {% endwith %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>


    <!-- import javascript cool animations -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

    <script type="text/javascript"
            src="{{ url_for('static', filename='index.js') }}"></script>
</body>
</html>

Movie Recommendation Website /src/website/templates/change_username.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Username</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="Style.css">
</head>
<body>
    <div class="container mt-5">
        <h2>Change Username</h2>
        <p>Email: {{ var }} </p>
        <form method="POST">
            <div class="mb-3">
                <label for="new_username" class="form-label">New Username</label>
                <input type="text" class="form-control" id="new_username" name="new_username" required>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    <!--Bootstrap JS-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Movie Recommendation Website /src/website/templates/home.html
{% extends "base.html" %}

{% block content %}
    <h1>This is the home page</h1>
    <div>
        <h2>Recommendations</h2>
        <ul>
            {% for recommendation in recommendations %}
                <li>{{ recommendation.title }}</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

Movie Recommendation Website /src/website/templates/login.html
{% extends "base.html" %} 
{% block title %} Login {% endblock %} 

{% block content %}
 
<form method="POST">
<div class="shadow p-3 mb-5 bg-body-tertiary rounded" >
    <h3 align="center" id="log_in" style="color: white;">Login</h3>

    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control"
         id="email" name="email" placeholder="Enter email"
         >
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control"
         id="password" name="password" placeholder="Enter password"
         >
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</div>
</form>

{% endblock %}

Movie Recommendation Website /src/website/templates/newquiz.html
{% extends "base.html" %}

{% block title %} New Quiz {% endblock %}

{% block content %}

<h1 style="align-items: center;">Welcome to the Quiz!</h1>

    {% if stage == 'genre_selection' %}
<div class="container mt-3 quiz-container">
    <form method="POST" class="genre-selection-form">
        <h2> 1. Select Genres</h2>
        <div class="form-group3" style="color: black; margin-top: 2rem;">
            {% for genre in genre_list %}
            <div class="form-check genre-checkbox">
                <input class="form-check-input" type="checkbox" name="s{{ loop.index }}" value="{{ genre }}">
                <label class="form-check-label" for="s{{ loop.index }}">
                    {{ genre }}
                </label>
            </div>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary" style="margin-top: 2rem;">Submit Genres</button>
    </form>
</div>

    {% elif stage == 'actor_display' %}
<div class="container mt-3 quiz-container">
    <form method="POST" class="genre-selection-form">
        <h2>Actors by Selected Genres:</h2>
        <div class="actors-by-genre">
            {% for genre, actors in actor_list.items() %}
            <h2>{{ genre }}</h2>
            <div class="actor-list">
                {% for actor in actors %}
                <div class="form-check actor-checkbox">
                    <input class="form-check-input" type="checkbox" name="a{{ loop.index }}" value="{{ actor }}">
                    <label class="form-check-label" for=" a{{ loop.index }}">
                        {{ actor }}
                    </label>
                </div>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary" style="margin-top: 2rem;">Submit Actors</button>
    </form>
</div>

    {% elif stage == 'director_display' %}
<div class="container mt-3 quiz-container">
    <form method="POST" class="director-selection-form">
        <h2>Directors by Selected Genres:</h2>
        <div class="directors-by-genre">
            {% for genre, directors in director_list.items() %}
            <h2>{{ genre }}</h2>
            <div class="director-list">
                {% for director in directors %}
                <div class="form-check director-checkbox">
                    <input class="form-check-input" type="checkbox" name="d{{ loop.index }}" value="{{ director }}">
                    <label class="form-check-label" for="d{{ loop.index }}">
                        {{ director }}
                    </label>
                </div>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary" style="margin-top: 2rem;">Submit Directors</button>
    </form>
</div>


    {% elif stage == 'language_display' %}
<div class="container mt-3 quiz-container">
    <form method="POST" class="language-selection-form">
        <h2>Language:</h2>
        <div class="language">
            {% for language in language_list %}
            <div class="language-list">
                <div class="form-check language-checkbox">
                    <input class="form-check-input" type="checkbox" name="l{{ loop.index }}" value="{{ language }}">
                    <label class="form-check-label" for="l{{ loop.index }}">
                        {{ language }}
                    </label>
                </div>
            </div>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary" style="margin-top: 2rem;">Submit Languages</button>
    </form>
</div>

    {% elif stage == 'movie_display' %}
<form method="POST">
    <div class="movie-container" style="margin-top: 5rem;">
        {% for key in displayed.keys() %}
        <div class="form-group2" style="color: white;">
            <div style="width: 200px; height: 50px; font-size: 12;">
                <p>{{ displayed[key]['title']}} ({{ displayed[key]['year'] }})</p>
            </div>
            <img src="{{ displayed[key]['url'] }}" alt="Movie Poster" style="height: 270px; width: 200px; border: 2px solid white;">

            <div class="checkboxes">
                <input type="checkbox" id="w{{ key }}" name="w{{ key }}" value="{{ displayed[key]['movie_id'] }}">
                <label for="w{{ key }}">Watched?</label>
            </div>
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary" style="margin-top: 0.5rem; margin-bottom: 0.5rem;">Submit</button>
    </div>
</form>

    {% elif stage == 'movie_display2' %}
<form method="POST">
    <div class="movie-container" style="margin-top: 5rem;">
        {% for key in displayed.keys() %}
        <div class="form-group2" style="color: white;">
            <div style="width: 200px; height: 50px; font-size: 12;">
                <p>{{ displayed[key]['title']}} ({{ displayed[key]['year'] }})</p>
            </div>
            <img src="{{ displayed[key]['url'] }}" alt="Movie Poster" style="height: 270px; width: 200px; border: 2px solid white;">

            <div class="checkboxes">
                <input type="checkbox" id="li{{ key }}" name="li{{ key }}" value="{{ displayed[key]['movie_id'] }}">
                <label for="li{{ key }}">Liked?</label>

                <input type="checkbox" id="dl{{ key }}" name="dl{{ key }}" value="{{ displayed[key]['movie_id'] }}">
                <label for="dl{{ key }}">Disliked?</label>
            </div>
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary" style="margin-top: 0.5rem; margin-bottom: 0.5rem;">Submit</button>
    </div>
</form>

    {% elif stage == 'movie_display3' %}
<form method="POST">
    <div class="movie-container" style="margin-top: 5rem;">
        {% for key in displayed.keys() %}
        <div class="form-group2" style="color: white;">
            <div style="width: 200px; height: 50px; font-size: 12;">
                <p>{{ displayed[key]['title']}} ({{ displayed[key]['year'] }})</p>
            </div>
            <img src="{{ displayed[key]['url'] }}" alt="Movie Poster" style="height: 270px; width: 200px; border: 2px solid white;">
        </div>
        {% endfor %}
    </div>
    <div class="quiz-actions">
        <a href="{{ url_for('views.home') }}" class="btn btn-primary">Return to Home</a>
    </div>
</form>

    {% endif %}

<div class="quiz-actions">
    <a href="{{ url_for('views.reset_quiz') }}" class="btn btn-primary">Start Over</a>
</div>

{% endblock %}

Movie Recommendation Website /src/website/templates/profile.html
{% extends "base.html" %}
{% block title %} Similar Quiz {% endblock %}
{% block content %}

<form method="POST">
    <div class="movie-container" style="margin-top: 5rem;">
        {% for key in displayed_recommendations.keys() %}
        <div class="form-group2" style="color: white;">
            <div style="width: 200px; height: 50px; font-size: 12;">
                <p>{{ displayed_recommendations[key]['title']}} ({{ displayed_recommendations[key]['year'] }})</p>
            </div>
            <img src="{{ displayed_recommendations[key]['url'] }}" alt="Movie Poster" style="height: 270px; width: 200px; border: 2px solid white;">

            <div class="checkboxes">
                <input type="checkbox" id="w{{ key }}" name="w{{ key }}" value="{{ displayed_recommendations[key]['movie_id'] }}">
                <label for="w{{ key }}">Watched</label>

                <input type="checkbox" id="ni{{ key }}" name="ni{{ key }}" value="{{ displayed_recommendations[key]['movie_id'] }}">
                <label for="ni{{ key }}">Not Interested</label>
            </div>
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary" style="margin-top: 0.5rem; margin-bottom: 0.5rem;">Submit</button>
    </div>
    <div class="movie-container" style="margin-top: 5rem;">
        {% for key in displayed_watched.keys() %}
        <div class="form-group2" style="color: white;">
            <div style="width: 200px; height: 50px; font-size: 12;">
                <p>{{ displayed_watched[key]['title']}} ({{ displayed_watched[key]['year'] }})</p>
            </div>
            <img src="{{ displayed_watched[key]['url'] }}" alt="Movie Poster" style="height: 270px; width: 200px; border: 2px solid white;">

        </div>
        {% endfor %}
    </div>

</form>
{% endblock %}

Movie Recommendation Website /src/website/templates/quiz.html
{% extends "base.html" %} 
{% block title %} Quiz {% endblock %} 

<h1>Looking for Recommendations?</h1>
<h3>You're at the right place.</h3>

{% block content %} 
<h1 class="text1">Looking for a Recommendation?</h1>
<h3 class="text2">You're in the right place.</h3>
<br>
<!-- New Recommendations -->
<div class="quiz_container">
    <a href="/newquiz">
    <button class="box" id="box1" name="t1">
        New Recommendation
        <br>
        <p style="font-size: small;">Interested in something different? <br> Tailored suggestions based on new input and preferences.</p>
    </button>
    </a>
    <a href="/quizsimilar">
    <button class="box" id="box2" name="'t2">
        Similar Recommendation
        <br>
        <p style="font-size: small;">Tailored suggestions based on past viewing history and your preferences.</p>
    </button>
    </a>
</div>



{% endblock %}

Movie Recommendation Website /src/website/templates/quizsimilar.html
{% extends "base.html" %}
{% block title %} Similar Quiz {% endblock %}
{% block content %}

<form method="POST">
    <div class="movie-container" style="margin-top: 5rem;">
        {% for key in displayed.keys() %}
        <div class="form-group2" style="color: white;">
            <div style="width: 200px; height: 50px; font-size: 12;">
                <p>{{ displayed[key]['title']}} ({{ displayed[key]['year'] }})</p>
            </div>
            <img src="{{ displayed[key]['url'] }}" alt="Movie Poster" style="height: 270px; width: 200px; border: 2px solid white;">

            <div class="checkboxes">
                <input type="checkbox" id="w{{ key }}" name="w{{ key }}" value="{{ displayed[key]['movie_id'] }}">
                <label for="w{{ key }}">Watched</label>

                <input type="checkbox" id="ni{{ key }}" name="ni{{ key }}" value="{{ displayed[key]['movie_id'] }}">
                <label for="ni{{ key }}">Not Interested</label>
            </div>
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary" style="margin-top: 0.5rem; margin-bottom: 0.5rem;">Submit</button>
    </div>
</form>
{% endblock %}

Movie Recommendation Website /src/website/templates/sign_up.html
{% extends "base.html" %} 
{% block title %} Sign Up {% endblock %} 

{% block content %} 

<form method="POST">
<div class="shadow p-3 mb-5 bg-body-tertiary rounded" >
    <h3 align="center" id="sign-up" style="color: white;">Sign Up</h3>
    
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control"
         id="email" name="email" placeholder="Enter email"
         >
    </div>

    <div class="form-group">
        <label for="username">User Name</label>
        <input type="text" class="form-control"
         id="username" name="username" placeholder="Enter User Name"
         >
    </div>

    <div class="form-group">
        <label for="password1">Password</label>
        <input type="password" class="form-control"
         id="password1" name="password1" placeholder="Enter password"
         >
    </div>

    <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input type="password" class="form-control"
         id="password2" name="password2" placeholder="Confirm password"
         >
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</div>
</form>

{% endblock %}